version: "3"

services:
  minecraft-java-server:
    image: itzg/minecraft-server:java17
    container_name: infrared-dev-minecraft-java-server
    restart: "no"
    volumes:
      - ../dev/minecraft-java:/data
    ports:
      - 25566:25565/tcp
    environment:
      EULA: "TRUE"
      VERSION: "1.19.4"
      TYPE: PAPER
      #TYPE: "FORGE"
      #FORGE_VERSION: "43.1.1"
    networks:
      - infrared
    labels:
      - infrared.java.servers.devserver.gateways=[default]
      - infrared.java.servers.devserver.domains=[*]
      - infrared.java.servers.devserver.address=:25566

  minecraft-bedrock-server:
    image: itzg/minecraft-bedrock-server:latest
    container_name: infrared-dev-minecraft-bedrock-server
    restart: "no"
    volumes:
      - ../dev/minecraft-bedrock:/data
    ports:
      - 19133:19132/udp
    environment:
      EULA: "TRUE"
    networks:
      - infrared
    labels:
      - infrared.bedrock.servers.devserver.gateways=[default]
      - infrared.bedrock.servers.devserver.domains=[*]
      - infrared.bedrock.servers.devserver.address=:19133

  haproxy:
    image: haproxy
    container_name: infrared-dev-haproxy
    networks:
      - infrared
    volumes:
      - ../dev/haproxy:/usr/local/etc/haproxy:ro
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - 25567:25565/tcp

  redis:
    image: redis
    container_name: infrared-dev-redis
    ports:
      - 6379:6379/tcp
    networks:
      - infrared

networks:
  infrared:
    name: infrared
