version: "3"

services:
  infrared:
    image: haveachin/infrared:2.0.0-alpha.13
    container_name: infrared
    restart: always
    ports:
      # Port for Java Edition
      - 25565:25565/tcp
      # Port for Bedrock Edition
      - 19132:19132/udp
      # API
      #- 8080:8080/tcp
      # Prometheus
      #- 9070:9070/tcp
    volumes:
      - ../dev:/infrared
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - infrared

  #redis:
  #  image: redis
  #  container_name: infrared-redis
  #  restart: always
  #  networks:
  #    - infrared

networks:
  infrared:
    name: infrared